 
const admin = 'admin';

const routes = {
    home: "/",
    nam: "/collection1?mapl_sp=1",
    nu: "/collection2?mapl_sp=2",
    treem: "/collection3?mapl_sp=3", 
    login: "/login",
    test: "/test",
    searchProduct: `/search`,
    infoProduct: "/infoProduct",
    cart: "/cart",
    cart_test: "/cart_test",
    payment: "/payment",
    addProduct: "/admin/addProduct",
    paymentResult: "/paymentResult",
    myOrder: "/myOrder",
    manageOrder: "/admin/manageOrder",
    manageProduct: "/admin/manageProduct", 
    detailProduct: "/admin/manageProduct/detailProduct",    
    infoAccount: "/infoAccount",
    printOrder: "/admin/printOrder",  
    adminLogin: "/admin/AdminLogin",
    manageAccountStaff: "/admin/ManageAccountStaff",
    manageAccountCustomer: "/admin/manageAccountCustomer",
    addVoucher: "/admin/addVoucher",
    manageVoucher: "/admin/manageVoucher",
    searchVoucher: "/admin/SearchVoucher",
    reviewProduct: "/reviewProduct",
    statistic: "/admin/Statistic",
    collection: "/collection",
    collection1: "/collection1",
    collection2: "/collection2",
    collection3: "/collection3",
    setData: "/SetData",
}
export default routes;