const admin = "admin";

const routes = {
  home: "/",
  login: "/login",
  test: "/test",
  searchProduct: `/search`,
  infoProduct: "/infoProduct",
  cart: "/cart",
  cart_test: "/cart_test",
  payment: "/payment",
  addProduct: "/admin/addProduct",
  paymentResult: "/paymentResult",
  myOrder: "/myOrder",
  manageOrder: "/admin/manageOrder",
  manageProduct: "/admin/manageProduct",
  detailProduct: "/admin/manageProduct/detailProduct",
  infoAccount: "/infoAccount",
  printOrder: "/admin/printOrder",
  adminLogin: "/admin/AdminLogin",
  manageAccountStaff: "/admin/ManageAccountStaff",
  manageAccountCustomer: "/admin/manageAccountCustomer",
  addVoucher: "/admin/addVoucher",
  manageVoucher: "/admin/manageVoucher",
  searchVoucher: "/admin/SearchVoucher",
  reviewProduct: "/reviewProduct",
  statistic: "/admin/Statistic",
  collection: "/collection",
  setData: "/SetData",
};
export default routes;
